# Generated by Django 3.2.8 on 2021-12-06 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_cupo_maximo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Capacidad_de_utofinanciamiento',
            new_name='Capacidad_de_autofinanciamiento',
        ),
        migrations.AddField(
            model_name='evento',
            name='Duracion_en_horas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AddField(
            model_name='evento',
            name='estatus',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default=('Pendiente', 'Pendiente'), max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(default=eventos.models.Responsable, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.responsable'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='male_avatar.svg', null=True, upload_to=''),
        ),
    ]
