# Generated by Django 3.2.8 on 2021-12-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20211205_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='modalidad',
            field=models.CharField(choices=[('En Linea', 'En Linea'), ('Presencial', 'Presencial'), ('Mixta', 'Mixta')], max_length=30, null=True),
        ),
    ]
